// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VARIATIONALSEGMENTATIONPLUGIN_H
#define VARIATIONALSEGMENTATIONPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "variationalSegmentationPluginExport.h"

class VARIATIONALSEGMENTATIONPLUGIN_EXPORT variationalSegmentationPluginPrivate;

class VARIATIONALSEGMENTATIONPLUGIN_EXPORT variationalSegmentationPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)
    
public:
    variationalSegmentationPlugin(QObject *parent = 0);
    ~variationalSegmentationPlugin(void);
    
    virtual bool initialize(void);
    virtual bool uninitialize(void);
    
    virtual QString name(void) const;
    virtual QString identifier(void) const;
    virtual QString description(void) const;
    virtual QString contact(void) const;
    virtual QString version (void) const;
    virtual QStringList authors(void) const;
    virtual QStringList contributors(void) const;
    virtual QStringList dependencies(void) const;
    
    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;
    
private:
    variationalSegmentationPluginPrivate *d;
};

#endif
