// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "variationalSegmentation.h"

#include <dtkCore/dtkAbstractProcessFactory.h>

// /////////////////////////////////////////////////////////////////
// variationalSegmentationPrivate
// /////////////////////////////////////////////////////////////////

class variationalSegmentationPrivate
{
public:
};

// /////////////////////////////////////////////////////////////////
// variationalSegmentation
// /////////////////////////////////////////////////////////////////

variationalSegmentation::variationalSegmentation(void) : dtkAbstractProcess(), d(new variationalSegmentationPrivate)
{
    
}

variationalSegmentation::~variationalSegmentation(void)
{
    
}

bool variationalSegmentation::registered(void)
{
    return dtkAbstractProcessFactory::instance()->registerProcessType("variationalSegmentation", createVariationalSegmentation);
}

QString variationalSegmentation::description(void) const
{
    return "variationalSegmentation";
}

// /////////////////////////////////////////////////////////////////
// Type instantiation
// /////////////////////////////////////////////////////////////////

dtkAbstractProcess *createVariationalSegmentation(void)
{
    return new variationalSegmentation;
}
