// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VARIATIONALSEGMENTATIONPLUGINEXPORT_H
#define VARIATIONALSEGMENTATIONPLUGINEXPORT_H

#ifdef WIN32
    #ifdef variationalSegmentationPlugin_EXPORTS
        #define VARIATIONALSEGMENTATIONPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define VARIATIONALSEGMENTATIONPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define VARIATIONALSEGMENTATIONPLUGIN_EXPORT
#endif

#endif
